param(
    [Parameter(Mandatory = $true)][string]$Tag
)

$ErrorActionPreference = 'Continue'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$relay = 'C:\Users\Ahmed\multiplex-app-patch'
$muxd = 'C:\Users\Ahmed\muxd'
$artifactRoot = Join-Path $root 'artifacts\reliability'
$artifactDir = Join-Path $artifactRoot $Tag
$current = Join-Path $root 'CURRENT.md'
$failed = Join-Path $root 'CURRENT_FAILED.md'
New-Item -ItemType Directory -Force $artifactDir | Out-Null

$results = [ordered]@{}
$hardFail = $false

function Run-Gate {
    param(
        [string]$Name,
        [scriptblock]$Command,
        [string]$PositiveMarker
    )
    $log = Join-Path $artifactDir ($Name + '.log')
    & $Command *> $log
    $exit = $LASTEXITCODE
    $marker = $true
    if ($PositiveMarker) {
        $marker = [bool](Select-String -Path $log -SimpleMatch $PositiveMarker -Quiet)
    }
    $ok = ($exit -eq 0) -and $marker
    $results[$Name] = @{ ok = $ok; log = $log; exit = $exit }
    if (-not $ok) { $script:hardFail = $true }
    $status = 'FAIL'; if ($ok) { $status = 'PASS' }
    Write-Host "[$status] $Name exit=$exit log=$log"
}

Set-Location $root
Run-Gate 'dotnet-build' {
    dotnet build native\CodexLocalRetrieval.Native.Tests\CodexLocalRetrieval.Native.Tests.csproj `
        -c Release -m:1 -p:UseSharedCompilation=false
} 'Build succeeded.'

if (-not $hardFail) {
    Run-Gate 'dotnet-tests' {
        dotnet test native\CodexLocalRetrieval.Native.Tests\CodexLocalRetrieval.Native.Tests.csproj `
            -c Release --no-build --logger 'console;verbosity=minimal'
    } 'Passed!'
}

Set-Location $relay
Run-Gate 'relay-tests' {
    $env:NODE_PATH = "$env:TEMP\mux-relay-node-deps\node_modules"
    node --check server.js
    if ($LASTEXITCODE -eq 0) { node --test tests\relay.test.js }
} '# pass '

Set-Location $muxd
Run-Gate 'muxd-tests' {
    python -m py_compile muxd.py transcript_guardian.py
    if ($LASTEXITCODE -eq 0) { python -m unittest discover -s tests -p 'test_*.py' }
} 'OK (skipped='

Set-Location $root
$head = git log -1 --pretty='%h %s'
$appDirty = git status --porcelain
$relayDirty = git -C $relay status --porcelain
$muxdDirty = git -C $muxd status --porcelain

$overall = 'GREEN - acceptable checkpoint'
if ($hardFail) { $overall = 'RED - DO NOT ACCEPT' }
$lines = @(
    '# CURRENT -- machine-generated by tools/run_gates.ps1. DO NOT HAND-EDIT.'
    ''
    "Overall: **$overall**"
    ''
    "- Tag: ``$Tag``"
    "- Date: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz')"
    "- Accepted tag: ``$Tag``"
    "- App HEAD: $head"
    "- App tree: $(if ($appDirty) { 'DIRTY' } else { 'CLEAN' })"
    "- Relay tree: $(if ($relayDirty) { 'DIRTY' } else { 'CLEAN' })"
    "- muxd tree: $(if ($muxdDirty) { 'DIRTY' } else { 'CLEAN' })"
    ''
    '## Gates'
    ''
)
foreach ($name in $results.Keys) {
    $state = 'FAIL'; if ($results[$name].ok) { $state = 'PASS' }
    $lines += "- **$name**: $state -- exit=$($results[$name].exit), log=$($results[$name].log)"
}
$lines += @(
    ''
    '## Residuals'
    ''
    'Residual work and queue status live in LOOPS.md. A green checkpoint is not final deployment'
    'until every loop in that ledger is done.'
)

$target = $current
if ($hardFail) { $target = $failed }
$lines | Out-File -FilePath $target -Encoding utf8
Write-Host "State written to $target"
if ($hardFail) { exit 1 }
exit 0
