param(
    [Parameter(Mandatory = $true)][string]$Tag
)

$ErrorActionPreference = 'Continue'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$relay = 'C:\Users\Ahmed\multiplex-app-patch'
$muxd = 'C:\Users\Ahmed\muxd'
$artifactRoot = Join-Path $root 'artifacts\reliability'
$artifactDir = Join-Path $artifactRoot $Tag
$current = Join-Path $root 'CURRENT.md'
$failed = Join-Path $root 'CURRENT_FAILED.md'
New-Item -ItemType Directory -Force $artifactDir | Out-Null

$results = [ordered]@{}
$hardFail = $false
$previousAcceptedTag = 'none'
if (Test-Path $current) {
    $acceptedLine = Select-String -Path $current -Pattern '^- Accepted tag: `([^`]+)`' | Select-Object -First 1
    if ($acceptedLine -and $acceptedLine.Matches.Count -gt 0) {
        $previousAcceptedTag = $acceptedLine.Matches[0].Groups[1].Value
    }
}

function Run-Gate {
    param(
        [string]$Name,
        [scriptblock]$Command,
        [string]$PositiveMarker
    )
    $log = Join-Path $artifactDir ($Name + '.log')
    & $Command *> $log
    $exit = $LASTEXITCODE
    $marker = $true
    if ($PositiveMarker) {
        $marker = [bool](Select-String -Path $log -SimpleMatch $PositiveMarker -Quiet)
    }
    $ok = ($exit -eq 0) -and $marker
    $results[$Name] = @{ ok = $ok; log = $log; exit = $exit }
    if (-not $ok) { $script:hardFail = $true }
    $status = 'FAIL'; if ($ok) { $status = 'PASS' }
    Write-Host "[$status] $Name exit=$exit log=$log"
}

function Get-Head {
    param([string]$Repo)
    return (& git -C $Repo log -1 --pretty='%H %s')
}

function Get-SourceStatus {
    param(
        [string]$Repo,
        [string[]]$Excludes = @()
    )
    $args = @('-C', $Repo, 'status', '--porcelain', '--untracked-files=all', '--', '.')
    foreach ($exclude in $Excludes) {
        $args += ":(exclude)$exclude"
    }
    return @(& git @args)
}

Set-Location $root
Run-Gate 'dotnet-build' {
    dotnet build native\CodexLocalRetrieval.Native.Tests\CodexLocalRetrieval.Native.Tests.csproj `
        -c Release -m:1 -p:UseSharedCompilation=false
} 'Build succeeded.'
$dotnetBuildPassed = $results['dotnet-build'].ok

if ($dotnetBuildPassed) {
    Run-Gate 'native-app-build' {
        dotnet build native\CodexLocalRetrieval.Native\CodexLocalRetrieval.Native.csproj `
            -c Release -m:1 -p:UseSharedCompilation=false
    } 'Build succeeded.'
}

if ($dotnetBuildPassed -and $results['native-app-build'].ok) {
    Run-Gate 'dotnet-tests' {
        dotnet test native\CodexLocalRetrieval.Native.Tests\CodexLocalRetrieval.Native.Tests.csproj `
            -c Release --no-build --logger 'console;verbosity=minimal' `
            --filter 'TestCategory!=RealStore&TestCategory!=LiveCodex' `
            --blame-hang --blame-hang-timeout 3m --blame-hang-dump-type mini
    } 'Passed!'
}

$projectionArtifact = Join-Path $artifactDir 'projects-projection.json'
if ($dotnetBuildPassed) {
    Run-Gate 'projection-contract' {
        dotnet run --project tools\ProjectionContractProbe\ProjectionContractProbe.csproj `
            -c Release -- $projectionArtifact
    } 'projects-projection.json'
}

Set-Location $relay
Run-Gate 'relay-tests' {
    $env:NODE_PATH = "$env:TEMP\mux-relay-node-deps\node_modules"
    $env:MUX_PROJECTION_ARTIFACT = $projectionArtifact
    node --check server.js
    if ($LASTEXITCODE -eq 0) { node --test tests\relay.test.js }
} '# pass '

Set-Location $muxd
Run-Gate 'muxd-tests' {
    python -m py_compile muxd.py transcript_guardian.py
    if ($LASTEXITCODE -eq 0) { python -m unittest discover -s tests -p 'test_*.py' }
} ''

Set-Location $root
$appHead = Get-Head $root
$relayHead = Get-Head $relay
$muxdHead = Get-Head $muxd
$appDirty = Get-SourceStatus $root
$relayDirty = Get-SourceStatus $relay
$muxdDirty = Get-SourceStatus $muxd @(
    'live-tabs.json',
    'live-tabs.json.bak',
    'sessions.json',
    'sessions.json.bak'
)
$provenanceOk = -not ($appDirty -or $relayDirty -or $muxdDirty)
$results['source-provenance'] = @{
    ok = $provenanceOk
    log = Join-Path $artifactDir 'source-provenance.json'
    exit = $(if ($provenanceOk) { 0 } else { 1 })
}
if (-not $provenanceOk) { $hardFail = $true }
@{
    app = @{ head = $appHead; dirty = @($appDirty) }
    relay = @{ head = $relayHead; dirty = @($relayDirty) }
    muxd = @{ head = $muxdHead; dirty = @($muxdDirty) }
} | ConvertTo-Json -Depth 4 | Out-File -FilePath $results['source-provenance'].log -Encoding utf8
Write-Host "[$(if ($provenanceOk) { 'PASS' } else { 'FAIL' })] source-provenance log=$($results['source-provenance'].log)"

$overall = 'GREEN - acceptable checkpoint'
if ($hardFail) { $overall = 'RED - DO NOT ACCEPT' }
$acceptedTag = $Tag
if ($hardFail) { $acceptedTag = $previousAcceptedTag }
$lines = @(
    '# CURRENT -- machine-generated by tools/run_gates.ps1. DO NOT HAND-EDIT.'
    ''
    "Overall: **$overall**"
    ''
    "- Tag: ``$Tag``"
    "- Date: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz')"
    "- Accepted tag: ``$acceptedTag``"
    "- App HEAD: $appHead"
    "- Relay HEAD: $relayHead"
    "- muxd HEAD: $muxdHead"
    "- App source tree: $(if ($appDirty) { 'DIRTY' } else { 'CLEAN' })"
    "- Relay source tree: $(if ($relayDirty) { 'DIRTY' } else { 'CLEAN' })"
    "- muxd source tree: $(if ($muxdDirty) { 'DIRTY' } else { 'CLEAN' })"
    ''
    '## Gates'
    ''
)
foreach ($name in $results.Keys) {
    $state = 'FAIL'; if ($results[$name].ok) { $state = 'PASS' }
    $lines += "- **$name**: $state -- exit=$($results[$name].exit), log=$($results[$name].log)"
}
$lines += @(
    ''
    '## Residuals'
    ''
    'Residual work and queue status live in LOOPS.md. A green checkpoint is not final deployment'
    'until every loop in that ledger is done.'
)

$target = $current
if ($hardFail) { $target = $failed }
$lines | Out-File -FilePath $target -Encoding utf8
Write-Host "State written to $target"
if ($hardFail) { exit 1 }
exit 0
